name: Deploy
on:
  workflow_dispatch:
    branches: main
  push:
    branches: main

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          cache: true

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
          HOST_KEY: ${{ secrets.HOST_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          SOURCE: "dist/"
          TARGET: "html/"
        run: |
          mkdir ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "$HOST_KEY" > ~/.ssh/known_hosts
          rsync -avz -e "ssh -o IdentitiesOnly=yes -i ~/.ssh/deploy_key" $SOURCE $USER@$HOST:$TARGET --delete
          rm -rf ~/.ssh
